name: "trabalho-final"

services:
  postgres_dev:
    container_name: "postgres-dev"
    image: postgres:16-alpine3.19
    env_file:
      - ./.env
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
